### ISSUE TITLE
Generate License Analyze YML for Open Source Check

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#1501]
Scope
---
To check licenses of used dependencies we need to generate analyze-result.yml and hand over to Open Source office by their standardized workflow.

Notes  
---
- Dev Dependencies are not relevant
- Only what probably is published in NPM package is relevant: Assets, Utilities, Components, Components-JS/-Angular/-React (also the stuff on CDN, previously part of the package in V1)
- Documentation: 
[5 OSS Review Toolkit (ORT) Technical Architecture-v15-20210706_175542.pdf](https://github.com/porscheui/porsche-design-system/files/6771260/5.OSS.Review.Toolkit.ORT.Technical.Architecture-v15-20210706_175542.pdf)
[1. Analyzer.ORT Integration-v28-20210706_175407.pdf](https://github.com/porscheui/porsche-design-system/files/6771262/1.Analyzer.ORT.Integration-v28-20210706_175407.pdf)

Acceptance criteria
---
- [x] Generate analzye-results.yml
- [x] Setup lean workflow to trigger re-analysis of dependencies
- [x] #1551

File: [analyzer-result.yml.zip](https://github.com/porscheui/porsche-design-system/files/6801191/analyzer-result.yml.zip)

Content:
```yml
---
repository:
  vcs:
    type: "Git"
    url: "git@github.com:porscheui/porsche-design-system.git"
    revision: "e7f164a722ead90b28e585bc31c15857fbfd0310"
    path: ""
  vcs_processed:
    type: "Git"
    url: "ssh://git@github.com/porscheui/porsche-design-system.git"
    revision: "e7f164a722ead90b28e585bc31c15857fbfd0310"
    path: ""
  config: {}
analyzer:
  start_time: "2021-07-12T11:58:39.992486Z"
  end_time: "2021-07-12T12:06:12.884450Z"
  environment:
    ort_version: "57b114a"
    java_version: "11.0.8"
    os: "Linux"
    processors: 6
    max_memory: 3141533696
    variables:
      JAVA_HOME: "/opt/java/openjdk"
      ANDROID_HOME: "/opt/android-sdk"
      GOPATH: "/go"
    tool_versions: {}
  config:
    ignore_tool_versions: false
    allow_dynamic_versions: false
  result:
    projects:
    - id: "NPM::.aws-sam/build/Function/package.json:"
      definition_file_path: ".aws-sam/build/Function/package.json"
      declared_licenses: []
      declared_licenses_processed: {}
      vcs:
        type: ""
        url: ""
        revision: ""
        path: ""
      vcs_processed:
        type: "Git"
        url: "ssh://git@github.com/porscheui/porsche-design-system.git"
        revision: "04cb6490d9b33dba210ec7a6af66213f7c6707db"
        path: ".aws-sam/build/Function"
      homepage_url: ""
      scopes: []
    - id: "NPM::aws/lambda/cloud-front-s3-logs-reorganizer/package.json:"
      definition_file_path: "aws/lambda/cloud-front-s3-logs-reorganizer/package.json"
      declared_licenses: []
      declared_licenses_processed: {}
      vcs:
        type: ""
        url: ""
        revision: ""
        path: ""
      vcs_processed:
        type: "Git"
        url: "ssh://git@github.com/porscheui/porsche-design-system.git"
        revision: "04cb6490d9b33dba210ec7a6af66213f7c6707db"
        path: "aws/lambda/cloud-front-s3-logs-reorganizer"
      homepage_url: ""
      scopes: []
    - id: "NPM::aws/lambda/cloud-front-storefront-redirect-to-trailing-slash/package.json:"
      definition_file_path: "aws/lambda/cloud-front-storefront-redirect-to-trailing-slash/package.json"
      declared_licenses: []
      declared_licenses_processed: {}
      vcs:
        type: ""
        url: ""
        revision: ""
        path: ""
      vcs_processed:
        type: "Git"
        url: "ssh://git@github.com/porscheui/porsche-design-system.git"
        revision: "04cb6490d9b33dba210ec7a6af66213f7c6707db"
        path: "aws/lambda/cloud-front-storefront-redirect-to-trailing-slash"
      homepage_url: ""
      scopes: []
    - id: "NPM::aws/lambda/cloud-front-storefront-rewrite-index-html/package.json:"
      definition_file_path: "aws/lambda/cloud-front-storefront-rewrite-index-html/package.json"
      declared_licenses: []
      declared_licenses_processed: {}
      vcs:
        type: ""
        url: ""
        revision: ""
        path: ""
      vcs_processed:
        type: "Git"
        url: "ssh://git@github.com/porscheui/porsche-design-system.git"
        revision: "04cb6490d9b33dba210ec7a6af66213f7c6707db"
        path: "aws/lambda/cloud-front-storefront-rewrite-index-html"
      homepage_url: ""
      scopes: []
    - id: "NPM::packages/assets/dist/package.json:"
      definition_file_path: "packages/assets/dist/package.json"
      declared_licenses: []
      declared_licenses_processed: {}
      vcs:
        type: ""
        url: ""
        revision: ""
        path: ""
      vcs_processed:
        type: "Git"
        url: "ssh://git@github.com/porscheui/porsche-design-system.git"
        revision: "04cb6490d9b33dba210ec7a6af66213f7c6707db"
        path: "packages/assets/dist"
      homepage_url: ""
      scopes: []
    - id: "NPM::packages/components-angular/projects/components-wrapper/package.json:"
      definition_file_path: "packages/components-angular/projects/components-wrapper/package.json"
      declared_licenses: []
      declared_licenses_processed: {}
      vcs:
        type: ""
        url: ""
        revision: ""
        path: ""
      vcs_processed:
        type: "Git"
        url: "ssh://git@github.com/porscheui/porsche-design-system.git"
        revision: "04cb6490d9b33dba210ec7a6af66213f7c6707db"
        path: "packages/components-angular/projects/components-wrapper"
      homepage_url: ""
      scopes: []
    - id: "NPM::packages/components-js/projects/components-wrapper/package.json:"
      definition_file_path: "packages/components-js/projects/components-wrapper/package.json"
      declared_licenses: []
      declared_licenses_processed: {}
      vcs:
        type: ""
        url: ""
        revision: ""
        path: ""
      vcs_processed:
        type: "Git"
        url: "ssh://git@github.com/porscheui/porsche-design-system.git"
        revision: "04cb6490d9b33dba210ec7a6af66213f7c6707db"
        path: "packages/components-js/projects/components-wrapper"
      homepage_url: ""
      scopes: []
    - id: "NPM::packages/components-react/projects/components-wrapper/package.json:"
      definition_file_path: "packages/components-react/projects/components-wrapper/package.json"
      declared_licenses: []
      declared_licenses_processed: {}
      vcs:
        type: ""
        url: ""
        revision: ""
        path: ""
      vcs_processed:
        type: "Git"
        url: "ssh://git@github.com/porscheui/porsche-design-system.git"
        revision: "04cb6490d9b33dba210ec7a6af66213f7c6707db"
        path: "packages/components-react/projects/components-wrapper"
      homepage_url: ""
      scopes: []
    - id: "Yarn::create-athena-partition:1.0.0"
      definition_file_path: "aws/lambda/create-athena-partition/package.json"
      declared_licenses: []
      declared_licenses_processed: {}
      vcs:
        type: ""
        url: ""
        revision: ""
        path: ""
      vcs_processed:
        type: "Git"
        url: "ssh://git@github.com/porscheui/porsche-design-system.git"
        revision: "e7f164a722ead90b28e585bc31c15857fbfd0310"
        path: "aws/lambda/create-athena-partition"
      homepage_url: ""
      scopes:
      - name: "dependencies"
        dependencies:
        - id: "NPM::athena-express:6.0.4"
          dependencies:
          - id: "NPM::csvtojson:2.0.10"
            dependencies:
            - id: "NPM::bluebird:3.7.2"
            - id: "NPM::lodash:4.17.21"
            - id: "NPM::strip-bom:2.0.0"
              dependencies:
              - id: "NPM::is-utf8:0.2.1"
      - name: "devDependencies"
        dependencies: []
    - id: "Yarn::package.json:"
      definition_file_path: "package.json"
      declared_licenses: []
      declared_licenses_processed: {}
      vcs:
        type: ""
        url: ""
        revision: ""
        path: ""
      vcs_processed:
        type: "Git"
        url: "ssh://git@github.com/porscheui/porsche-design-system.git"
        revision: "e7f164a722ead90b28e585bc31c15857fbfd0310"
        path: ""
      homepage_url: ""
      scopes: []
    packages:
    - package:
        id: "NPM::athena-express:6.0.4"
        purl: "pkg:npm/athena-express@6.0.4"
        authors:
        - "Gary Arora"
        declared_licenses:
        - "MIT"
        declared_licenses_processed:
          spdx_expression: "MIT"
        description: "Athena-Express makes it easier to execute SQL queries on Amazon\
          \ Athena by consolidating & astracting several methods in the AWS SDK"
        homepage_url: "https://github.com/ghdna/athena-express#readme"
        binary_artifact:
          url: ""
          hash:
            value: ""
            algorithm: ""
        source_artifact:
          url: "https://registry.npmjs.org/athena-express/-/athena-express-6.0.4.tgz"
          hash:
            value: "bb457dcc967686faea2138f934828a331b98c8f6"
            algorithm: "SHA-1"
        vcs:
          type: "Git"
          url: "git+https://github.com/ghdna/athena-express.git"
          revision: "109f8c784bd3efded24de25646b6ab137e980b4c"
          path: ""
        vcs_processed:
          type: "Git"
          url: "https://github.com/ghdna/athena-express.git"
          revision: "109f8c784bd3efded24de25646b6ab137e980b4c"
          path: ""
      curations: []
    - package:
        id: "NPM::bluebird:3.7.2"
        purl: "pkg:npm/bluebird@3.7.2"
        authors:
        - "Petka Antonov"
        declared_licenses:
        - "MIT"
        declared_licenses_processed:
          spdx_expression: "MIT"
        description: "Full featured Promises/A+ implementation with exceptionally\
          \ good performance"
        homepage_url: "https://github.com/petkaantonov/bluebird"
        binary_artifact:
          url: ""
          hash:
            value: ""
            algorithm: ""
        source_artifact:
          url: "https://registry.npmjs.org/bluebird/-/bluebird-3.7.2.tgz"
          hash:
            value: "9f229c15be272454ffa973ace0dbee79a1b0c36f"
            algorithm: "SHA-1"
        vcs:
          type: "Git"
          url: "git://github.com/petkaantonov/bluebird.git"
          revision: "750bd7f87fefaa0f918a6f0a25caec32ffdaddd8"
          path: ""
        vcs_processed:
          type: "Git"
          url: "https://github.com/petkaantonov/bluebird.git"
          revision: "750bd7f87fefaa0f918a6f0a25caec32ffdaddd8"
          path: ""
      curations: []
    - package:
        id: "NPM::csvtojson:2.0.10"
        purl: "pkg:npm/csvtojson@2.0.10"
        authors:
        - "Keyang Xiang"
        declared_licenses:
        - "MIT"
        declared_licenses_processed:
          spdx_expression: "MIT"
        description: "A tool concentrating on converting csv data to JSON with customised\
          \ parser supporting"
        homepage_url: "https://github.com/Keyang/node-csvtojson"
        binary_artifact:
          url: ""
          hash:
            value: ""
            algorithm: ""
        source_artifact:
          url: "https://registry.npmjs.org/csvtojson/-/csvtojson-2.0.10.tgz"
          hash:
            value: "11e7242cc630da54efce7958a45f443210357574"
            algorithm: "SHA-1"
        vcs:
          type: "Git"
          url: "git+https://github.com/Keyang/node-csvtojson.git"
          revision: "abf5f59dce172d78adc3c62f4e9ff5b356e3565c"
          path: ""
        vcs_processed:
          type: "Git"
          url: "https://github.com/Keyang/node-csvtojson.git"
          revision: "abf5f59dce172d78adc3c62f4e9ff5b356e3565c"
          path: ""
      curations: []
    - package:
        id: "NPM::is-utf8:0.2.1"
        purl: "pkg:npm/is-utf8@0.2.1"
        authors:
        - "wayfind"
        declared_licenses:
        - "MIT"
        declared_licenses_processed:
          spdx_expression: "MIT"
        description: "Detect if a buffer is utf8 encoded."
        homepage_url: "https://github.com/wayfind/is-utf8#readme"
        binary_artifact:
          url: ""
          hash:
            value: ""
            algorithm: ""
        source_artifact:
          url: "https://registry.npmjs.org/is-utf8/-/is-utf8-0.2.1.tgz"
          hash:
            value: "4b0da1442104d1b336340e80797e865cf39f7d72"
            algorithm: "SHA-1"
        vcs:
          type: "Git"
          url: "git+https://github.com/wayfind/is-utf8.git"
          revision: "709df7202f9c3f93cdc2463b352dd80d8de9ce0b"
          path: ""
        vcs_processed:
          type: "Git"
          url: "https://github.com/wayfind/is-utf8.git"
          revision: "709df7202f9c3f93cdc2463b352dd80d8de9ce0b"
          path: ""
      curations: []
    - package:
        id: "NPM::lodash:4.17.21"
        purl: "pkg:npm/lodash@4.17.21"
        authors:
        - "John-David Dalton"
        declared_licenses:
        - "MIT"
        declared_licenses_processed:
          spdx_expression: "MIT"
        description: "Lodash modular utilities."
        homepage_url: "https://lodash.com/"
        binary_artifact:
          url: ""
          hash:
            value: ""
            algorithm: ""
        source_artifact:
          url: "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz"
          hash:
            value: "679591c564c3bffaae8454cf0b3df370c3d6911c"
            algorithm: "SHA-1"
        vcs:
          type: "Git"
          url: "git+https://github.com/lodash/lodash.git"
          revision: "c6e281b878b315c7a10d90f9c2af4cdb112d9625"
          path: ""
        vcs_processed:
          type: "Git"
          url: "https://github.com/lodash/lodash.git"
          revision: "c6e281b878b315c7a10d90f9c2af4cdb112d9625"
          path: ""
      curations: []
    - package:
        id: "NPM::strip-bom:2.0.0"
        purl: "pkg:npm/strip-bom@2.0.0"
        authors:
        - "Sindre Sorhus"
        declared_licenses:
        - "MIT"
        declared_licenses_processed:
          spdx_expression: "MIT"
        description: "Strip UTF-8 byte order mark (BOM) from a string/buffer"
        homepage_url: "https://github.com/sindresorhus/strip-bom"
        binary_artifact:
          url: ""
          hash:
            value: ""
            algorithm: ""
        source_artifact:
          url: "https://registry.npmjs.org/strip-bom/-/strip-bom-2.0.0.tgz"
          hash:
            value: "6219a85616520491f35788bdbf1447a99c7e6b0e"
            algorithm: "SHA-1"
        vcs:
          type: "Git"
          url: "https://github.com/sindresorhus/strip-bom"
          revision: "851b9c126dba9561cc14ef3dc2634dcc11df4d11"
          path: ""
        vcs_processed:
          type: "Git"
          url: "https://github.com/sindresorhus/strip-bom.git"
          revision: "851b9c126dba9561cc14ef3dc2634dcc11df4d11"
          path: ""
      curations: []
    issues:
      'NPM::.aws-sam/build/Function/package.json:':
      - timestamp: "2021-07-12T11:58:46.785157Z"
        source: "NPM"
        message: "Resolving dependencies for 'package.json' failed with: IllegalArgumentException:\
          \ No lockfile found in '.aws-sam/build/Function'. This potentially results\
          \ in unstable versions of dependencies. To allow this, enable support for\
          \ dynamic versions."
        severity: "ERROR"
      'NPM::aws/lambda/cloud-front-s3-logs-reorganizer/package.json:':
      - timestamp: "2021-07-12T11:58:46.840826Z"
        source: "NPM"
        message: "Resolving dependencies for 'package.json' failed with: IllegalArgumentException:\
          \ No lockfile found in 'aws/lambda/cloud-front-s3-logs-reorganizer'. This\
          \ potentially results in unstable versions of dependencies. To allow this,\
          \ enable support for dynamic versions."
        severity: "ERROR"
      'NPM::aws/lambda/cloud-front-storefront-redirect-to-trailing-slash/package.json:':
      - timestamp: "2021-07-12T11:58:46.882424Z"
        source: "NPM"
        message: "Resolving dependencies for 'package.json' failed with: IllegalArgumentException:\
          \ No lockfile found in 'aws/lambda/cloud-front-storefront-redirect-to-trailing-slash'.\
          \ This potentially results in unstable versions of dependencies. To allow\
          \ this, enable support for dynamic versions."
        severity: "ERROR"
      'NPM::aws/lambda/cloud-front-storefront-rewrite-index-html/package.json:':
      - timestamp: "2021-07-12T11:58:46.929557Z"
        source: "NPM"
        message: "Resolving dependencies for 'package.json' failed with: IllegalArgumentException:\
          \ No lockfile found in 'aws/lambda/cloud-front-storefront-rewrite-index-html'.\
          \ This potentially results in unstable versions of dependencies. To allow\
          \ this, enable support for dynamic versions."
        severity: "ERROR"
      'NPM::packages/assets/dist/package.json:':
      - timestamp: "2021-07-12T11:58:46.973099Z"
        source: "NPM"
        message: "Resolving dependencies for 'package.json' failed with: IllegalArgumentException:\
          \ No lockfile found in 'packages/assets/dist'. This potentially results\
          \ in unstable versions of dependencies. To allow this, enable support for\
          \ dynamic versions."
        severity: "ERROR"
      'NPM::packages/components-angular/projects/components-wrapper/package.json:':
      - timestamp: "2021-07-12T11:58:47.010533Z"
        source: "NPM"
        message: "Resolving dependencies for 'package.json' failed with: IllegalArgumentException:\
          \ No lockfile found in 'packages/components-angular/projects/components-wrapper'.\
          \ This potentially results in unstable versions of dependencies. To allow\
          \ this, enable support for dynamic versions."
        severity: "ERROR"
      'NPM::packages/components-js/projects/components-wrapper/package.json:':
      - timestamp: "2021-07-12T11:58:47.055506Z"
        source: "NPM"
        message: "Resolving dependencies for 'package.json' failed with: IllegalArgumentException:\
          \ No lockfile found in 'packages/components-js/projects/components-wrapper'.\
          \ This potentially results in unstable versions of dependencies. To allow\
          \ this, enable support for dynamic versions."
        severity: "ERROR"
      'NPM::packages/components-react/projects/components-wrapper/package.json:':
      - timestamp: "2021-07-12T11:58:47.097600Z"
        source: "NPM"
        message: "Resolving dependencies for 'package.json' failed with: IllegalArgumentException:\
          \ No lockfile found in 'packages/components-react/projects/components-wrapper'.\
          \ This potentially results in unstable versions of dependencies. To allow\
          \ this, enable support for dynamic versions."
        severity: "ERROR"
      'Yarn::package.json:':
      - timestamp: "2021-07-12T12:05:58.141488Z"
        source: "Yarn"
        message: "Resolving dependencies for 'package.json' failed with: IOException:\
          \ Running 'yarn install --ignore-scripts --ignore-engines' in '/project'\
          \ failed with exit code 1:\nerror An unexpected error occurred: \"https://porscheui.jfrog.io/porscheui/api/npm/npm/@porsche-design-system/prettier-config/-/@porsche-design-system/prettier-config-1.0.0.tgz:\
          \ Request failed \\\"401 Unauthorized\\\"\".\n"
        severity: "ERROR"
    has_issues: true
scanner: null
advisor: null
evaluator: null
```
