### ISSUE TITLE
[FEATURE] - SCSS Flexible Gradient Mixin

### ISSUE THREAD

**Issue by leifmarcus** [porsche-design-system/porsche-design-system#3533]
### Portfolio

No Portfolio

### ART and Team

BaM / EVEH

### Contact Details

markus.wessollek@mhp.com

### Problem

As discussed in our alignment meeting with @neuncreative and @muellernaumann, we discussed the usage of PDS Gradients.

Currently, the PDS only provides a gradient that fades to one color. In some cases, this does not look nice, for instance, when the background color of the surrounding elements is `theme-dark-background-base`.

We discussed, that it would be nice, to have a gradient helper, that is able to generate different gradients based on the background color, the surrounding elements have.

### Solution ideas and examples

# Solution
In the PCOM frontend we use a sass helper, that can generate color gradients with different colors.

## Types of Gradients

1. **Translucent:** When the gradient is used to cover an image to make the text on the image more readable, the gradient should not cover the underlaying image completely. Therefore, the gradient should end at a percentage of 90%, so that parts of the image still shining through
2. **Full coverage:** Sometimes, the gradient is used to fade out imagery to a dark background. In such cases, the gradient should cover the image completely, so that the transition to the surrounding is seamless.

## SCSS Gradient Mixin

The following code is an example implementation of a SCSS mixin, that you could offer to generate different kinds of gradients ([See in SCSS Playground](https://sass-lang.com/playground/#eJydVttuozAQfecrRt1WKlJDuN/6Eu0+7Wc44IAVsJFt2o26/fcdh6RJWok1VaSA8TnjOfaMZ4JgMyoKd4ooVVaiE/Lu2XHuh1qtdEt7uqqJ3K+2pNo3Uoy8xldFS/jhU58G4fMXZCW4lkTpVSdeERb7+ItnYD2t2dgjMs/zIq9mkC1rWsSR3dbfRujjer2GhnIqiaaABOgYp0RCI0nNKNdgPK0B6YCT+jDQI2UzEEl6ePtltL7D/VEzEH6ASik4jm5wP4XoKOGIRDe46sbK2FZUgxag5UjNc0/pMPlADlTClqJ6eGGKbbvTqpLqUXI16yi0Wg+qXK87IhXlr0LuvUr0a0oU483qjFdrZ7MbeaUZUsxunXdhNRn+AMLjpK6E/5zn0424EnakU9SFNwdgw3Zo5mp2+gxnRfB4HMG0c17VEt7Q07polnRDS0rwvcIF/+HJDouR4ELuRdb4JHUhSL3QmuAjIYy8wpaQxaELUeDFtoQ0zZCQe6ktIckjF+LEnhAXiQtJaL9LsW8Iub3oKEANaWK/rWGEGrIFuxQkORIye4JfxBgZkb1ovHyQYC3ZDwIXithLLAkYdr7/cIS6z847bCgmzncSJFiQHkVuYst+04oErWf2554XJp0WLJCHGFlB4WX26YQehal9sKcxBkpk7VCC/sSBveLY4IsFmZGEJpWs8yLB+yxNvcA6LzJ0KFtwPwW+CfNgSV6YK3bBHesH0bczA//fnffbiq2AfKmDx4KKhQYrrxm+Mt0iqmEvlF8V5t9mpusAMTXWWgKXYgaDFAOV+nDmflrBm+kATGH+6ACA8WNLsBOyJ/qGpcUAf6GjO42PrdBa9PgisTnRaKtmkk6F2di7jMTu+OHsiEWHwSbGlTjVirEzDxSFc/ixaQF95QKFbXr2h53agdMiC6r/h6MlHsIw0w5cqCV86jamew7P8GJtCpW5FuUSONcthjNdp47jnXEz7p/aFF51Y00/bcC88Jk1rtvYBQtc04z1f06JdQM=))

```scss
@use "sass:color";

$pds-theme-dark-background-base: #0e0e12;
$pds-theme-dark-contrast-low: #404044;
$pds-theme-dark-contrast-medium: #88898c;
$pds-theme-dark-contrast-high: #afb0b3;

/// generate the linear gradient based ont he type
/// @param {Color} $color any css color
/// @param {Boolean} $translucent set to true to keep the layer below visible
/// @returns the linear gradient based on https://larsenwork.com/easing-gradients/
@function pds-generate-linear-gradient ($color: $pds-theme-dark-background-base, $translucent: false) {
  @return if($translucent, (
      color.change($color, $alpha: 0.9) 0%,
      color.change($color, $alpha: 0.889) 8.3%,
      color.change($color, $alpha: 0.856) 16.2%,
      color.change($color, $alpha: 0.806) 23.9%,
      color.change($color, $alpha: 0.742) 31.4%,
      color.change($color, $alpha: 0.667) 38.6%,
      color.change($color, $alpha: 0.583) 45.6%,
      color.change($color, $alpha: 0.495) 52.3%,
      color.change($color, $alpha: 0.405) 58.9%,
      color.change($color, $alpha: 0.317) 65.2%,
      color.change($color, $alpha: 0.233) 71.4%,
      color.change($color, $alpha: 0.158) 77.4%,
      color.change($color, $alpha: 0.094) 83.3%,
      color.change($color, $alpha: 0.044) 89%,
      color.change($color, $alpha: 0.011) 94.5%,
      color.change($color, $alpha: 0) 100%
    ),(
      color.change($color, $alpha: 1) 0%,
      color.change($color, $alpha: 0.987) 3.4%,
      color.change($color, $alpha: 0.951) 7.9%,
      color.change($color, $alpha: 0.896) 13.4%,
      color.change($color, $alpha: 0.825) 19.7%,
      color.change($color, $alpha: 0.741) 26.6%,
      color.change($color, $alpha: 0.648) 34%,
      color.change($color, $alpha: 0.55) 41.9%,
      color.change($color, $alpha: 0.45) 49.9%,
      color.change($color, $alpha: 0.352) 58%,
      color.change($color, $alpha: 0.259) 66.1%,
      color.change($color, $alpha: 0.175) 73.9%,
      color.change($color, $alpha: 0.104) 81.3%,
      color.change($color, $alpha: 0.049) 88.3%,
      color.change($color, $alpha: 0.013) 94.5%,
      color.change($color, $alpha: 0) 100%
    )
  );
}

/// generates a linear gradient to transparent with a given color
/// It will render a background property with a linear gradient.
/// @param {Color} $color the css color in any format
/// @param {top | left | bottom | right} $direction the direction of the gradient
/// @param {Boolean} $translucent if the background should shine through or not.
@mixin pds-gradient($color: $pds-theme-dark-background-base, $direction: top, $translucent: false) {
  background: linear-gradient(
    to $direction,
    pds-generate-linear-gradient($color, $translucent)
  );
}
```

## Usage

```scss
.gradient-theme-dark-background-base {
  @include pds-gradient($pds-theme-dark-background-base, top, true);
}

.gradient-theme-dark-contrast-low {
  @include pds-gradient($pds-theme-dark-contrast-low, bottom, false);
}
```

### Business priority

High

**Comment by kroofy** [comment]
Thanks for bringing this up. Would be great if we consider non SCSS use-cases too, maybe something like this can be considered?

```css
:root {
  --easing-gradient-color: 14, 14, 18;
  --easing-gradient-direction: bottom;
}

.easing-gradient {
  background: linear-gradient(
    to var(--easing-gradient-direction, top),
    rgb(var(--easing-gradient-color)) 0%,
    rgba(var(--easing-gradient-color), 0.987) 3.4%,
    rgba(var(--easing-gradient-color), 0.951) 7.9%,
    rgba(var(--easing-gradient-color), 0.896) 13.4%,
    rgba(var(--easing-gradient-color), 0.825) 19.7%,
    rgba(var(--easing-gradient-color), 0.741) 26.6%,
    rgba(var(--easing-gradient-color), 0.648) 34%,
    rgba(var(--easing-gradient-color), 0.55) 41.9%,
    rgba(var(--easing-gradient-color), 0.45) 49.9%,
    rgba(var(--easing-gradient-color), 0.352) 58%,
    rgba(var(--easing-gradient-color), 0.259) 66.1%,
    rgba(var(--easing-gradient-color), 0.175) 73.9%,
    rgba(var(--easing-gradient-color), 0.104) 81.3%,
    rgba(var(--easing-gradient-color), 0.049) 88.3%,
    rgba(var(--easing-gradient-color), 0.013) 94.5%,
    rgba(var(--easing-gradient-color), 0) 100%
  );
}

.easing-gradient[data-type="translucent"] {
  background: linear-gradient(
    to var(--easing-gradient-direction, top),
    rgba(var(--easing-gradient-color), 0.9) 0%,
    rgba(var(--easing-gradient-color), 0.889) 8.3%,
    rgba(var(--easing-gradient-color), 0.856) 16.2%,
    rgba(var(--easing-gradient-color), 0.806) 23.9%,
    rgba(var(--easing-gradient-color), 0.742) 31.4%,
    rgba(var(--easing-gradient-color), 0.667) 38.6%,
    rgba(var(--easing-gradient-color), 0.583) 45.6%,
    rgba(var(--easing-gradient-color), 0.495) 52.3%,
    rgba(var(--easing-gradient-color), 0.405) 58.9%,
    rgba(var(--easing-gradient-color), 0.317) 65.2%,
    rgba(var(--easing-gradient-color), 0.233) 71.4%,
    rgba(var(--easing-gradient-color), 0.158) 77.4%,
    rgba(var(--easing-gradient-color), 0.094) 83.3%,
    rgba(var(--easing-gradient-color), 0.044) 89%,
    rgba(var(--easing-gradient-color), 0.011) 94.5%,
    rgba(var(--easing-gradient-color), 0) 100%
  );
}
```

**Comment by leifmarcus** [comment]
@kroofy, Wouldn’t it be better, to have the gradient in a custom property instead of a class name? I was just thinking, how to apply the gradient to a `::after` or `::before` element.

```css
/* somewhere on the root level */
:root {
  --pds-easing-gradient: linear-gradient(
    to var(--easing-gradient-direction, top),
    rgba(var(--easing-gradient-color), 0.9) 0%,
    rgba(var(--easing-gradient-color), 0.889) 8.3%,
    rgba(var(--easing-gradient-color), 0.856) 16.2%,
    rgba(var(--easing-gradient-color), 0.806) 23.9%,
    rgba(var(--easing-gradient-color), 0.742) 31.4%,
    rgba(var(--easing-gradient-color), 0.667) 38.6%,
    rgba(var(--easing-gradient-color), 0.583) 45.6%,
    rgba(var(--easing-gradient-color), 0.495) 52.3%,
    rgba(var(--easing-gradient-color), 0.405) 58.9%,
    rgba(var(--easing-gradient-color), 0.317) 65.2%,
    rgba(var(--easing-gradient-color), 0.233) 71.4%,
    rgba(var(--easing-gradient-color), 0.158) 77.4%,
    rgba(var(--easing-gradient-color), 0.094) 83.3%,
    rgba(var(--easing-gradient-color), 0.044) 89%,
    rgba(var(--easing-gradient-color), 0.011) 94.5%,
    rgba(var(--easing-gradient-color), 0) 100%
  );
}

.my.element::after {
  /* ... */
  --pds-easing-gradient-direction: bottom;
  --pds-easing-gradient-color: 14, 14, 18;
  backgrund: var(--pds-easing-gradient);
}

```
